### ISSUE TITLE
Cache directory

### ISSUE THREAD

**Issue by johndodev** [ezyang/htmlpurifier#105]
Hello,

I have a warning in production : *Directory var/cache/html_purifier/HTML not writable, please chmod to 777*. 

but when I deploy I delete cache files and recreate it : 

    rm -rf var/cache/* && mkdir var/cache/html_purifier && chmod 777 var/cache/html_purifier

and I configured the cache as this : 

    'Cache.SerializerPath' => __DIR__.'/../../var/cache/html_purifier'

so, two things : 

- I don't understand why the library can't access a folder it create himself. I didn't create the HTML folder, the code of the library did. It shoul'd be allowed to write in it.

- Actually, even the "html_purifier" folder should be created by the library. As a developper my job is to make the "cache" folder writable and config librairies which need it, not to create every "root" folder in it for each library.

For example, twig config is 

    'cache' => __DIR__.'/../../var/cache/twig',

but I never create this twig folder. Twig create it as 777, and furthermore chmod files with the umask I have in my index.php. 

I've read some code of Serailizer.php, _prepareDir and _testPermissions, I think it is just to complex for what it is supposed to do, and the use of it (developper have to create the folder) not user friendy.

Maybe have a look on [twig code](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Cache/Filesystem.php#L57-L85), and keep it simple ?

**Comment by Finesse** [comment]
@ezyang What about using [PSR-6](https://www.php-fig.org/psr/psr-6/) or [PSR-16](https://www.php-fig.org/psr/psr-16/) to cache data? What it will give:

1. Library users will be able to choose what cache to use (file, memcached, etc.)
2. You won't need to support the cache code in this library.

**Comment by ezyang** [comment]
Well, if someone submits a PR, I'd consider it :) But remember HTML Purifier needs to be easily installable by itself, without needing some other dependency to implement caching for it.

**Comment by Finesse** [comment]
@ezyang So must HTML Purifier be able to work with no dependencies at all (including dependencies installed automatically by Composer)?

**Comment by ezyang** [comment]
Yes; there'd have to be a good reason to add a dep.

**Comment by Finesse** [comment]
@ezyang I’m afraid such approach that doesn’t add a dependency will increase the library complexity because it will have 2 cache implementations: the default one and a PSR adapter.

I’d consider implementing a caching which requires the following installation:

```bash
composer require ezyang/htmlpurifier default-caching-library-or-any-other
```

Or with the following installation but with the cache off by default:

```bash
composer require ezyang/htmlpurifier
```

I wrote the benefits I see from a cache dependency in the comment above. But I think you better know what is better for the library.

**Comment by okainov** [comment]
What is the cache actually caching? In [docs](http://htmlpurifier.org/live/configdoc/plain.html) it says "you will see a definite performance degradation", but doesn't it depend on use case? 

If I apply HtmlPurifier for different strings (so it cannot be really cached), why should I get performance issues?  Or is it some internal cache? If so, then for sure it's better to be in /tmp :)

Also I agree that by default it should be either disabled (to do not raise warning messages out-of-the box) or have permission fixed by itself.

**Comment by roynasser** [comment]
Interested as well... When the html to be purified is always changing, what does the cache do? (This will help us understand how to better store the cache)...

(containerized app)

**Comment by pmochine** [comment]
Need help, I get the error:

Directory /var/www/staging/releases/10/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777

What should I do?

**Comment by edgreenberg** [comment]
So here we are in 2020 and composer still doesn't reliably install the serializer directory so that apache can write it.  My environment is centos 7, apache 2.4 and php-fpm 7.2.   I don't think that composer CAN get this right. I think that the problem is that the  contents of the DefinitionCache/Serializer directory should be in /tmp or some other place out of the vendor directory.  I wonder if I'm missing a configuration option.

**Comment by ignacio-dev** [comment]
Hello, was this issue ever solved? I am facing the same issue. The project is ready, working fine on dev, but not working on production at all.
